stages:
  - deploy-dev

deploy-job:
  stage: deploy-dev
  image: ruby:latest
  script:
      - gem install dpl
      - dpl --provider=heroku --app=$HEROKU_APP --api-key=$HEROKU_API_KEY
  only:
      - /^v[0-9]+(\.[0-9]+){2}(-[0-9]+)?$/